# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LeZhu' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LeZhu
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
   pod 'MJExtension', '~> 3.0.13'
   pod 'MBProgressHUD', '~> 1.0.0'
   pod 'SVProgressHUD', '~> 2.0.3'
   pod 'MJRefresh', '~> 3.1.12'
   pod 'PulsingHalo', '~> 0.2.3'
  pod 'JPush'
end
